// <auto-generated />
using System;
using Infrastructrue.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(MQTTLABDbContext))]
    partial class MQTTLABDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructrue.Database.Sensor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<long>("createdAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("key")
                        .HasMaxLength(32)
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasMaxLength(1)
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("key")
                        .IsUnique();

                    b.ToTable("t_sensor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
